global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter-1:9100' ]
        labels:
          node: node-exporter-1

  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent-1:8429']
        labels:
          node: vmagent-1

  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics-1:8428']
        labels:
          node: victoriametrics-1
